# Generated by Django 6.0.5 on 2026-05-26 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tsc_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('tenure_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Transferred', 'Transferred'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=100)),
                ('cbc_pathway', models.CharField(blank=True, choices=[('STEM', 'STEM'), ('Arts & Sports Science', 'Arts & Sports Science'), ('Social Sciences', 'Social Sciences')], max_length=50, null=True)),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('class_obj', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='academics.class')),
                ('stream', models.ForeignKey(db_column='stream_id', on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='academics.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
