# Generated by Django 6.0.5 on 2026-07-07 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_academicyear_unique_together_and_more'),
        ('core', '0002_staff_school_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('graduated', 'Graduated'), ('repeated', 'Repeated'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class'),
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('graduated', 'Graduated'), ('repeated', 'Repeated'), ('transferred', 'Transferred')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='core.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
