# Generated by Django 6.0.5 on 2026-05-26 10:47

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeductionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_year', models.IntegerField(unique=True)),
                ('shaf_rate', models.DecimalField(decimal_places=2, default=2.75, max_digits=5)),
                ('housing_levy_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('nssf_tier1_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('nssf_tier1_limit', models.DecimalField(decimal_places=2, default=8000, max_digits=10)),
                ('nssf_tier2_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('nssf_tier2_limit', models.DecimalField(decimal_places=2, default=72000, max_digits=10)),
                ('nhif_schedule', models.JSONField()),
                ('paye_brackets', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nhif_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nssf_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shaf_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_levy', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa B2C'), ('bank', 'Bank Transfer')], max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('processed_at', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='payroll.payrollentry')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.CharField(max_length=50, unique=True)),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.academicyear')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_runs', to='core.staff')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='academics.term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='core.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payroll.salarystructure'),
        ),
    ]
