# Generated by Django 6.0.5 on 2026-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_reconciliationlog_studentcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('tkash', 'T-Kash'), ('equity', 'Equity'), ('kcb', 'KCB'), ('coop', 'Co-op'), ('absa', 'ABSA'), ('stanbic', 'Stanbic'), ('scb', 'Standard Chartered'), ('dtb', 'DTB'), ('ncba', 'NCBA'), ('family', 'Family Bank'), ('im', 'I&M Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit', 'Credit Applied')], max_length=20),
        ),
    ]
