# Generated by Django 6.0.5 on 2026-05-26 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('client_system', models.CharField(max_length=100)),
                ('permissions', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='api_keys', to='core.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostBookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_number', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('loss_date', models.DateField()),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('lms_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.academicyear')),
                ('invoice_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoicelineitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lost_book_events', to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academics.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
