# Generated by Django 6.0.5 on 2026-05-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsubject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_taught', to='core.staff'),
        ),
        migrations.AddField(
            model_name='stream',
            name='class_obj',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subjects', to='core.department'),
        ),
        migrations.AddField(
            model_name='staffsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_teaching', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('class_obj', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='staffsubject',
            unique_together={('staff', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'term_number')},
        ),
    ]
