# Generated by Django 6.0.5 on 2026-06-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_school_class_school_stream_school_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(default='10c083d1-9424-45dd-adb3-4d26f6ae5974', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default='10c083d1-9424-45dd-adb3-4d26f6ae5974', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(default='10c083d1-9424-45dd-adb3-4d26f6ae5974', on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(default='10c083d1-9424-45dd-adb3-4d26f6ae5974', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default='10c083d1-9424-45dd-adb3-4d26f6ae5974', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.school'),
            preserve_default=False,
        ),
    ]
