# Generated by Django 6.0.5 on 2026-06-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicyear_school_alter_class_school_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'code')},
        ),
    ]
