# Generated by Django 6.0.5 on 2026-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('name', 'type', 'parent')},
        ),
    ]
